import { Patient } from '../models/patient';

export const patients: Patient[] = [
  {
    id: 'P001',
    firstName: 'Ahmed',
    lastName: 'Hassan',
    phone: '0101-234-5678',
    email: 'ahmed.hassan@email.com',
    dateOfBirth: '1988-03-15',
    gender: 'male',
    allergies: 'Penicillin',
    notes: 'Prefers morning appointments.',
    address: '12 Nile St, Cairo',
    isSmoker: true,
    totalBill: 1500,
    amountPaid: 800,
    trackingStatus: 'InTreatment',
    lastVisitDate: '2026-02-20',
    nextFollowUpDate: '2026-03-15',
    history: [
      { id: 'E001', date: '2026-01-10', type: 'status_change', description: 'Patient registered — status set to New.' },
      { id: 'E002', date: '2026-01-25', type: 'visit', description: 'Initial examination. Cavities found on teeth #14, #36.' },
      { id: 'E003', date: '2026-01-25', type: 'status_change', description: 'Status changed to InTreatment.' },
      { id: 'E004', date: '2026-02-20', type: 'visit', description: 'Filling done on tooth #14. Next: tooth #36.' },
      { id: 'E005', date: '2026-02-20', type: 'follow_up', description: 'Follow-up scheduled for 2026-03-15.' },
      { id: 'E006', date: '2026-02-20', type: 'payment', description: 'Payment of 800 EGP received.' },
    ],
    visits: [
      {
        id: 'V001', visitDate: '2026-01-25', diagnosis: 'Cavities on teeth #14 and #36',
        notes: 'Patient referred for fillings.',
        procedures: [
          { id: 'PR001', toothNumber: 14, procedureType: 'Examination', cost: 200 },
          { id: 'PR002', toothNumber: 36, procedureType: 'X-Ray', cost: 150 },
        ],
      },
      {
        id: 'V002', visitDate: '2026-02-20', diagnosis: 'Filling on tooth #14',
        procedures: [
          { id: 'PR003', toothNumber: 14, procedureType: 'Composite Filling', cost: 600 },
        ],
      },
    ],
    images: [],
  },
  {
    id: 'P002',
    firstName: 'Fatima',
    lastName: 'Ali',
    phone: '0112-345-6789',
    email: 'fatima.ali@email.com',
    dateOfBirth: '1995-07-22',
    gender: 'female',
    address: '45 Garden City, Cairo',
    isSmoker: false,
    totalBill: 3200,
    amountPaid: 3200,
    trackingStatus: 'FollowUpNeeded',
    lastVisitDate: '2026-02-05',
    nextFollowUpDate: '2026-03-10',
    history: [
      { id: 'E010', date: '2025-11-12', type: 'status_change', description: 'Patient registered — status set to New.' },
      { id: 'E011', date: '2025-11-12', type: 'visit', description: 'Routine cleaning and scaling.' },
      { id: 'E012', date: '2025-11-12', type: 'status_change', description: 'Status changed to InTreatment.' },
      { id: 'E013', date: '2026-01-08', type: 'visit', description: 'Root canal therapy on tooth #26.' },
      { id: 'E014', date: '2026-02-05', type: 'visit', description: 'Crown fitting on tooth #26.' },
      { id: 'E015', date: '2026-02-05', type: 'status_change', description: 'Status changed to FollowUpNeeded.' },
      { id: 'E016', date: '2026-02-05', type: 'follow_up', description: 'Follow-up scheduled for 2026-03-10 to check crown.' },
      { id: 'E017', date: '2026-01-08', type: 'payment', description: 'Payment of 2000 EGP received.' },
      { id: 'E018', date: '2026-02-05', type: 'payment', description: 'Payment of 1200 EGP received. Fully paid.' },
    ],
    visits: [
      {
        id: 'V010', visitDate: '2025-11-12', diagnosis: 'Routine cleaning needed',
        procedures: [
          { id: 'PR010', toothNumber: 0, procedureType: 'Scaling & Polishing', cost: 400 },
        ],
      },
      {
        id: 'V011', visitDate: '2026-01-08', diagnosis: 'Irreversible pulpitis on tooth #26',
        procedures: [
          { id: 'PR011', toothNumber: 26, procedureType: 'Root Canal Therapy', cost: 1800 },
        ],
      },
      {
        id: 'V012', visitDate: '2026-02-05', diagnosis: 'Crown fitting on tooth #26',
        procedures: [
          { id: 'PR012', toothNumber: 26, procedureType: 'Porcelain Crown', cost: 1000 },
        ],
      },
    ],
    images: [],
  },
  {
    id: 'P003',
    firstName: 'Mohamed',
    lastName: 'Ibrahim',
    phone: '0100-987-6543',
    email: 'mohamed.ibrahim@email.com',
    dateOfBirth: '1972-11-03',
    gender: 'male',
    allergies: 'Latex',
    notes: 'Diabetic — requires special care.',
    address: '8 Zamalek, Cairo',
    isSmoker: false,
    totalBill: 900,
    amountPaid: 900,
    trackingStatus: 'Completed',
    lastVisitDate: '2026-01-30',
    history: [
      { id: 'E020', date: '2025-10-05', type: 'status_change', description: 'Patient registered — status set to New.' },
      { id: 'E021', date: '2025-10-05', type: 'visit', description: 'Full dental examination.' },
      { id: 'E022', date: '2025-10-20', type: 'visit', description: 'Deep cleaning — upper and lower arches.' },
      { id: 'E023', date: '2025-10-20', type: 'status_change', description: 'Status changed to InTreatment.' },
      { id: 'E024', date: '2026-01-30', type: 'visit', description: 'Final check-up. No further treatment needed.' },
      { id: 'E025', date: '2026-01-30', type: 'status_change', description: 'Status changed to Completed.' },
      { id: 'E026', date: '2026-01-30', type: 'payment', description: 'Payment of 900 EGP received. Fully paid.' },
    ],
    visits: [
      {
        id: 'V020', visitDate: '2025-10-05', diagnosis: 'Full dental examination',
        procedures: [
          { id: 'PR020', toothNumber: 0, procedureType: 'Comprehensive Exam', cost: 300 },
        ],
      },
      {
        id: 'V021', visitDate: '2025-10-20', diagnosis: 'Periodontal disease — deep cleaning required',
        procedures: [
          { id: 'PR021', toothNumber: 0, procedureType: 'Deep Cleaning (Upper)', cost: 300 },
          { id: 'PR022', toothNumber: 0, procedureType: 'Deep Cleaning (Lower)', cost: 300 },
        ],
      },
    ],
    images: [],
  },
  {
    id: 'P004',
    firstName: 'Sara',
    lastName: 'Mahmoud',
    phone: '0122-111-2233',
    email: 'sara.mahmoud@email.com',
    dateOfBirth: '2001-05-18',
    gender: 'female',
    address: '90 Maadi, Cairo',
    isSmoker: false,
    totalBill: 0,
    amountPaid: 0,
    trackingStatus: 'New',
    history: [
      { id: 'E030', date: '2026-03-01', type: 'status_change', description: 'Patient registered — status set to New.' },
      { id: 'E031', date: '2026-03-01', type: 'note', description: 'Patient reports tooth pain in lower-right area.' },
    ],
    visits: [],
    images: [],
  },
  {
    id: 'P005',
    firstName: 'Youssef',
    lastName: 'Khaled',
    phone: '0155-444-5566',
    email: 'youssef.k@email.com',
    dateOfBirth: '1990-09-10',
    gender: 'male',
    notes: 'Anxious patient — needs gentle approach.',
    address: '3 Heliopolis, Cairo',
    isSmoker: true,
    totalBill: 2000,
    amountPaid: 500,
    trackingStatus: 'InTreatment',
    lastVisitDate: '2026-02-28',
    nextFollowUpDate: '2026-03-20',
    history: [
      { id: 'E040', date: '2026-02-01', type: 'status_change', description: 'Patient registered — status set to New.' },
      { id: 'E041', date: '2026-02-01', type: 'visit', description: 'Consultation — wisdom teeth extraction recommended.' },
      { id: 'E042', date: '2026-02-01', type: 'status_change', description: 'Status changed to InTreatment.' },
      { id: 'E043', date: '2026-02-28', type: 'visit', description: 'Extraction of tooth #38 (lower-left wisdom).' },
      { id: 'E044', date: '2026-02-28', type: 'follow_up', description: 'Follow-up scheduled for 2026-03-20 — extraction site check.' },
      { id: 'E045', date: '2026-02-28', type: 'payment', description: 'Payment of 500 EGP received.' },
    ],
    visits: [
      {
        id: 'V040', visitDate: '2026-02-01', diagnosis: 'Impacted wisdom teeth — extraction needed',
        procedures: [
          { id: 'PR040', toothNumber: 38, procedureType: 'Consultation & X-Ray', cost: 350 },
        ],
      },
      {
        id: 'V041', visitDate: '2026-02-28', diagnosis: 'Extraction of lower-left wisdom tooth',
        procedures: [
          { id: 'PR041', toothNumber: 38, procedureType: 'Surgical Extraction', cost: 1500 },
          { id: 'PR042', toothNumber: 38, procedureType: 'Sutures', cost: 150 },
        ],
      },
    ],
    images: [],
  },
  {
    id: 'P006',
    firstName: 'Nour',
    lastName: 'El-Din',
    phone: '0100-222-3344',
    email: 'nour.eldin@email.com',
    dateOfBirth: '1985-01-28',
    gender: 'female',
    address: '17 Dokki, Cairo',
    isSmoker: false,
    totalBill: 8000,
    amountPaid: 3000,
    trackingStatus: 'FollowUpNeeded',
    lastVisitDate: '2026-02-10',
    nextFollowUpDate: '2026-03-08',
    history: [
      { id: 'E050', date: '2025-12-15', type: 'status_change', description: 'Patient registered — status set to New.' },
      { id: 'E051', date: '2025-12-15', type: 'visit', description: 'Orthodontic consultation — braces recommended.' },
      { id: 'E052', date: '2026-01-10', type: 'visit', description: 'Upper and lower braces fitted.' },
      { id: 'E053', date: '2026-01-10', type: 'status_change', description: 'Status changed to InTreatment.' },
      { id: 'E054', date: '2026-02-10', type: 'visit', description: 'First adjustment appointment.' },
      { id: 'E055', date: '2026-02-10', type: 'status_change', description: 'Status changed to FollowUpNeeded.' },
      { id: 'E056', date: '2026-02-10', type: 'follow_up', description: 'Next adjustment scheduled for 2026-03-08.' },
      { id: 'E057', date: '2026-01-10', type: 'payment', description: 'Payment of 3000 EGP received.' },
    ],
    visits: [
      {
        id: 'V050', visitDate: '2025-12-15', diagnosis: 'Orthodontic consultation — Class II malocclusion',
        procedures: [
          { id: 'PR050', toothNumber: 0, procedureType: 'Orthodontic Consultation', cost: 500 },
          { id: 'PR051', toothNumber: 0, procedureType: 'Panoramic X-Ray', cost: 300 },
        ],
      },
      {
        id: 'V051', visitDate: '2026-01-10', diagnosis: 'Braces fitted — upper and lower arches',
        procedures: [
          { id: 'PR052', toothNumber: 0, procedureType: 'Metal Braces (Upper)', cost: 3000 },
          { id: 'PR053', toothNumber: 0, procedureType: 'Metal Braces (Lower)', cost: 3000 },
        ],
      },
      {
        id: 'V052', visitDate: '2026-02-10', diagnosis: 'First adjustment — wire tightening',
        procedures: [
          { id: 'PR054', toothNumber: 0, procedureType: 'Braces Adjustment', cost: 500 },
        ],
      },
    ],
    images: [],
  },
];
